import React, { useEffect, useRef, useState } from 'react';
import {
  Linking,
  Modal,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../theme/colors';
import { Snippet } from '../types/snippet';
import { copyToClipboard } from '../utils/clipboard';
import {
  formatAsciiTerminalCard,
  formatMarkdownTerminal,
  generateSvgTerminalCard,
} from '../utils/terminalCardFormatter';

interface TerminalEmulatorModalProps {
  visible: boolean;
  snippet: Snippet | null;
  onClose: () => void;
    onSaveSnippetOutput?: (
    snippetId: string,
    expectedOutput: string,
    duration: string,
    prompt: string,
    simulatedUser?: string,
    simulatedHost?: string,
    simulatedCwd?: string,
    simulatedComment?: string
  ) => void;
}

type TabMode = 'preview' | 'customize' | 'share';
type ThemeMode = 'cyberpunk' | 'tokyo' | 'dracula' | 'matrix' | 'minimal';
type PlaybackSpeed = '1x' | '2x' | 'instant';

export const TerminalEmulatorModal: React.FC<TerminalEmulatorModalProps> = ({
  visible,
  snippet,
  onClose,
  onSaveSnippetOutput,
}) => {
  if (!snippet) return null;

  // Synthesis fallback if snippet has no expected output yet
  const getDefaultOutput = (item: Snippet): string => {
    if (item.expectedOutput) return item.expectedOutput;
    if (item.category === 'Git') {
      return `[main 4f1a92e] Changes applied cleanly.\n 2 files changed, 18 insertions(+), 4 deletions(-)\n✔ Git operation completed in 48ms.`;
    }
    if (item.category === 'Docker') {
      return `Deleted Containers:\n4a29c1b3f940\nTotal reclaimed space: 4.82GB\n✔ Docker cleanup finished successfully.`;
    }
    if (item.category === 'Kubernetes') {
      return `NAME                          READY   STATUS    RESTARTS   AGE\npod/api-service-7f6d-x89p     1/1     Running   0          4d\n✔ Kubernetes resource synchronized.`;
    }
    if (item.category === 'Database') {
      return `NOTICE: table "records" analyzed (0.012 sec)\nCOPY 14,820 rows affected\n✔ Transaction committed (exit 0).`;
    }
    return `✔ Process finished with exit code 0\n  Output generated by DevVault Terminal Emulator`;
  };

  const [activeTab, setActiveTab] = useState<TabMode>('preview');
  const [username, setUsername] = useState(snippet.simulatedUser || 'ethan');
  const [hostname, setHostname] = useState(snippet.simulatedHost || 'devvault');
  const [cwd, setCwd] = useState(snippet.simulatedCwd || '~');
  const [promptSymbol, setPromptSymbol] = useState(
    (snippet.simulatedUser || 'ethan') === 'root' ? '#' : '$'
  );
  const [prompt, setPrompt] = useState(
    snippet.simulatedPrompt ||
      `${snippet.simulatedUser || 'ethan'}@${snippet.simulatedHost || 'devvault'}:${snippet.simulatedCwd || '~'}$`
  );
  const [comment, setComment] = useState(snippet.simulatedComment || '');
  const [expectedOutput, setExpectedOutput] = useState(getDefaultOutput(snippet));
  const [duration, setDuration] = useState(snippet.executionDuration || '120ms');
  const [exitCode, setExitCode] = useState(0);
  const [theme, setTheme] = useState<ThemeMode>('cyberpunk');
  const [speed, setSpeed] = useState<PlaybackSpeed>('1x');

  // Animation states
  const [displayedCommand, setDisplayedCommand] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isExecuting, setIsExecuting] = useState(false);
  const [showOutput, setShowOutput] = useState(false);
  const [cursorVisible, setCursorVisible] = useState(true);
  const [copiedNotification, setCopiedNotification] = useState<string | null>(null);
  const [saveSuccess, setSaveSuccess] = useState(false);

  // Sync state when snippet changes
  useEffect(() => {
    if (snippet) {
      const u = snippet.simulatedUser || 'ethan';
      const h = snippet.simulatedHost || 'devvault';
      const c = snippet.simulatedCwd || '~';
      const s = u === 'root' ? '#' : '$';
      setUsername(u);
      setHostname(h);
      setCwd(c);
      setPromptSymbol(s);
      setPrompt(snippet.simulatedPrompt || `${u}@${h}:${c}${s}`);
      setComment(snippet.simulatedComment || '');
      setExpectedOutput(getDefaultOutput(snippet));
      setDuration(snippet.executionDuration || '120ms');
      restartEmulation();
    }
  }, [snippet?.id, visible]);

  const applyMachinePreset = (user: string, host: string, dir: string, sym: string) => {
    setUsername(user);
    setHostname(host);
    setCwd(dir);
    setPromptSymbol(sym);
    setPrompt(`${user}@${host}:${dir}${sym}`);
  };

  const handleUsernameChange = (val: string) => {
    setUsername(val);
    const sym = val.trim() === 'root' ? '#' : promptSymbol;
    if (val.trim() === 'root' && promptSymbol === '$') setPromptSymbol('#');
    setPrompt(`${val}@${hostname}:${cwd}${sym}`);
  };

  const handleHostnameChange = (val: string) => {
    setHostname(val);
    setPrompt(`${username}@${val}:${cwd}${promptSymbol}`);
  };

  const handleCwdChange = (val: string) => {
    setCwd(val);
    setPrompt(`${username}@${hostname}:${val}${promptSymbol}`);
  };

  const handleSymbolChange = (sym: string) => {
    setPromptSymbol(sym);
    setPrompt(`${username}@${hostname}:${cwd}${sym}`);
  };

  // Cursor blink interval
  useEffect(() => {
    const timer = setInterval(() => {
      setCursorVisible((prev) => !prev);
    }, 530);
    return () => clearInterval(timer);
  }, []);

  // Run typing animation
  const animationTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const restartEmulation = () => {
    if (animationTimerRef.current) clearInterval(animationTimerRef.current);

    if (speed === 'instant') {
      setDisplayedCommand(snippet.content);
      setIsTyping(false);
      setIsExecuting(false);
      setShowOutput(true);
      return;
    }

    setDisplayedCommand('');
    setIsTyping(true);
    setIsExecuting(false);
    setShowOutput(false);

    const fullCommand = snippet.content;
    let charIndex = 0;
    const intervalMs = speed === '2x' ? 14 : 28;

    animationTimerRef.current = setInterval(() => {
      charIndex++;
      setDisplayedCommand(fullCommand.slice(0, charIndex));

      if (charIndex >= fullCommand.length) {
        if (animationTimerRef.current) clearInterval(animationTimerRef.current);
        setIsTyping(false);
        setIsExecuting(true);

        const executionPause = speed === '2x' ? 180 : 360;
        setTimeout(() => {
          setIsExecuting(false);
          setShowOutput(true);
        }, executionPause);
      }
    }, intervalMs);
  };

  useEffect(() => {
    if (visible && activeTab === 'preview') {
      restartEmulation();
    }
    return () => {
      if (animationTimerRef.current) clearInterval(animationTimerRef.current);
    };
  }, [speed]);

  const showToast = (msg: string) => {
    setCopiedNotification(msg);
    setTimeout(() => setCopiedNotification(null), 2400);
  };

  const handleCopyAscii = async () => {
    const ascii = formatAsciiTerminalCard({
      title: `${username}@${hostname}: ${snippet.title}`,
      prompt,
      username,
      hostname,
      cwd,
      promptSymbol,
      command: snippet.content,
      output: expectedOutput,
      duration,
      exitCode,
      theme,
      comment,
    });
    const ok = await copyToClipboard(ascii);
    if (ok) showToast('ASCII Terminal Card Copied!');
  };

  const handleCopyMarkdown = async () => {
    const md = formatMarkdownTerminal({
      prompt,
      username,
      hostname,
      cwd,
      promptSymbol,
      command: snippet.content,
      output: expectedOutput,
      duration,
      exitCode,
      comment,
    });
    const ok = await copyToClipboard(md);
    if (ok) showToast('Markdown Codeblock Copied!');
  };

  const handleShareTwitter = () => {
    const commentStr = comment.trim() ? `# ${comment.trim()}\n` : '';
    const text = `⚡ ${snippet.title}\n\n${commentStr}${prompt} ${snippet.content}\n\n${expectedOutput.slice(0, 100)}...\n\n#DevVault #Terminal #CLI`;
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
    Linking.openURL(url).catch(() => {});
  };

  const handleShareLinkedIn = () => {
    const commentStr = comment.trim() ? `# ${comment.trim()}\n` : '';
    const text = `⚡ ${snippet.title}\n\n${commentStr}${prompt} ${snippet.content}\n\n${expectedOutput}`;
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent('https://github.com')}&summary=${encodeURIComponent(text)}`;
    Linking.openURL(url).catch(() => {});
  };

  const handleDownloadSvg = () => {
    if (Platform.OS === 'web' && typeof document !== 'undefined') {
      const svg = generateSvgTerminalCard({
        title: `${username}@${hostname}: ${cwd} (zsh)`,
        prompt,
        username,
        hostname,
        cwd,
        promptSymbol,
        command: snippet.content,
        output: expectedOutput,
        duration,
        exitCode,
        theme,
        comment,
      });
      const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${snippet.id || 'devvault-terminal'}.svg`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      showToast('SVG Terminal Card Downloaded!');
    } else {
      handleCopyAscii();
    }
  };

  const handleSaveOutput = () => {
    if (onSaveSnippetOutput) {
      onSaveSnippetOutput(
        snippet.id,
        expectedOutput,
        duration,
        prompt,
        username,
        hostname,
        cwd,
        comment
      );
      setSaveSuccess(true);
      setTimeout(() => setSaveSuccess(false), 2200);
      showToast('Saved output & machine profile to recipe!');
    }
  };

  // Theme borders & shadows
  const getThemeStyle = () => {
    switch (theme) {
      case 'cyberpunk':
        return {
          borderColor: '#58a6ff',
          backgroundColor: '#090d12',
          ...(Platform.OS === 'web'
            ? ({
                boxShadow: '0 0 24px rgba(88, 166, 255, 0.25), 0 0 4px rgba(188, 140, 255, 0.3)',
              } as any)
            : {}),
        };
      case 'tokyo':
        return {
          borderColor: '#7aa2f7',
          backgroundColor: '#1a1b26',
          ...(Platform.OS === 'web'
            ? ({
                boxShadow: '0 0 20px rgba(122, 162, 247, 0.25)',
              } as any)
            : {}),
        };
      case 'dracula':
        return {
          borderColor: '#bd93f9',
          backgroundColor: '#282a36',
          ...(Platform.OS === 'web'
            ? ({
                boxShadow: '0 0 22px rgba(189, 147, 249, 0.25)',
              } as any)
            : {}),
        };
      case 'matrix':
        return {
          borderColor: '#3fb950',
          backgroundColor: '#0d1117',
          ...(Platform.OS === 'web'
            ? ({
                boxShadow: '0 0 20px rgba(63, 185, 80, 0.25)',
              } as any)
            : {}),
        };
      case 'minimal':
      default:
        return {
          borderColor: '#30363d',
          backgroundColor: '#161b22',
        };
    }
  };

  return (
    <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}>
      <View style={styles.overlay}>
        <View style={styles.modalContainer}>
          {/* Header */}
          <View style={styles.header}>
            <View style={styles.headerLeft}>
              <View style={styles.terminalIconWrap}>
                <Ionicons name="terminal" size={18} color={colors.accentGreen} />
              </View>
              <View>
                <Text style={styles.headerTitle}>Terminal Emulation & Social Card</Text>
                <Text style={styles.headerSubtitle} numberOfLines={1}>
                  {snippet.title}
                </Text>
              </View>
            </View>

            <TouchableOpacity onPress={onClose} style={styles.closeBtn}>
              <Ionicons name="close" size={20} color={colors.textSecondary} />
            </TouchableOpacity>
          </View>

          {/* Toast Notification Banner */}
          {copiedNotification && (
            <View style={styles.toastBanner}>
              <Ionicons name="checkmark-circle" size={16} color={colors.accentGreen} />
              <Text style={styles.toastText}>{copiedNotification}</Text>
            </View>
          )}

          {/* Tab Navigation */}
          <View style={styles.tabBar}>
            <TouchableOpacity
              style={[styles.tabBtn, activeTab === 'preview' && styles.tabBtnActive]}
              onPress={() => setActiveTab('preview')}
            >
              <Ionicons
                name="play-circle-outline"
                size={15}
                color={activeTab === 'preview' ? colors.primary : colors.textMuted}
              />
              <Text style={[styles.tabText, activeTab === 'preview' && styles.tabTextActive]}>
                Emulation Preview
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[styles.tabBtn, activeTab === 'customize' && styles.tabBtnActive]}
              onPress={() => setActiveTab('customize')}
            >
              <Ionicons
                name="options-outline"
                size={15}
                color={activeTab === 'customize' ? colors.primary : colors.textMuted}
              />
              <Text style={[styles.tabText, activeTab === 'customize' && styles.tabTextActive]}>
                Customize Output & Prompt
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[styles.tabBtn, activeTab === 'share' && styles.tabBtnActive]}
              onPress={() => setActiveTab('share')}
            >
              <Ionicons
                name="share-social-outline"
                size={15}
                color={activeTab === 'share' ? colors.primary : colors.textMuted}
              />
              <Text style={[styles.tabText, activeTab === 'share' && styles.tabTextActive]}>
                Social Sharing & Export
              </Text>
            </TouchableOpacity>
          </View>

          {/* Modal Body */}
          <ScrollView style={styles.body} contentContainerStyle={styles.scrollBody} showsVerticalScrollIndicator={true}>
            {/* 1. PREVIEW TAB */}
            {activeTab === 'preview' && (
              <View style={styles.tabContent}>
                {/* Simulated Terminal Window */}
                <View style={[styles.terminalCard, getThemeStyle()]}>
                  {/* macOS Title Bar */}
                  <View style={styles.terminalTitleBar}>
                    <View style={styles.trafficLights}>
                      <View style={[styles.trafficDot, { backgroundColor: '#ff5f56' }]} />
                      <View style={[styles.trafficDot, { backgroundColor: '#ffbd2e' }]} />
                      <View style={[styles.trafficDot, { backgroundColor: '#27c93f' }]} />
                    </View>

                    <Text style={styles.terminalTitleText} numberOfLines={1}>
                      {username}@{hostname}: {cwd} (zsh)
                    </Text>

                    <View style={styles.terminalStatusPills}>
                      <View style={styles.exitStatusPill}>
                        <Text style={styles.exitStatusText}>
                          {exitCode === 0 ? '● exit 0' : `✘ exit ${exitCode}`}
                        </Text>
                      </View>
                      <View style={styles.durationPill}>
                        <Text style={styles.durationText}>⚡ {duration}</Text>
                      </View>
                    </View>
                  </View>

                  {/* Terminal Screen Body */}
                  <View style={styles.terminalBody}>
                    {/* Shell Comment Line(s) */}
                    {comment.trim() ? (
                      <View style={styles.commentBlock}>
                        {comment
                          .split('\n')
                          .map((line) => line.trim())
                          .filter((l) => l.length > 0)
                          .map((line, idx) => (
                            <Text key={idx} style={styles.terminalCommentText}>
                              {line.startsWith('#') ? line : `# ${line}`}
                            </Text>
                          ))}
                      </View>
                    ) : null}

                    {/* Command line */}
                    <View style={styles.cliLine}>
                      <Text style={styles.promptText}>{prompt} </Text>
                      <Text style={styles.commandText}>
                        {displayedCommand}
                        {isTyping && cursorVisible && <Text style={styles.cursorText}>▋</Text>}
                      </Text>
                    </View>

                    {/* Execution in progress spinner */}
                    {isExecuting && (
                      <View style={styles.executingRow}>
                        <Ionicons name="sync" size={13} color={colors.primary} style={styles.spinnerIcon} />
                        <Text style={styles.executingText}>Running command...</Text>
                      </View>
                    )}

                    {/* Output section */}
                    {showOutput && (
                      <View style={styles.outputBox}>
                        <Text style={styles.outputText}>{expectedOutput}</Text>

                        {/* Trailing prompt with blinking cursor */}
                        <View style={[styles.cliLine, { marginTop: 12 }]}>
                          <Text style={styles.promptText}>{prompt} </Text>
                          {cursorVisible && <Text style={styles.cursorText}>▋</Text>}
                        </View>
                      </View>
                    )}
                  </View>
                </View>

                {/* Playback Controls Bar */}
                <View style={styles.playbackControls}>
                  <TouchableOpacity style={styles.replayBtn} onPress={restartEmulation} activeOpacity={0.8}>
                    <Ionicons name="refresh" size={14} color={colors.textInverse} />
                    <Text style={styles.replayBtnText}>Replay Emulation</Text>
                  </TouchableOpacity>

                  <View style={styles.speedButtonGroup}>
                    {(['1x', '2x', 'instant'] as PlaybackSpeed[]).map((spd) => (
                      <TouchableOpacity
                        key={spd}
                        style={[styles.speedBtn, speed === spd && styles.speedBtnActive]}
                        onPress={() => setSpeed(spd)}
                      >
                        <Text style={[styles.speedBtnText, speed === spd && styles.speedBtnTextActive]}>
                          {spd}
                        </Text>
                      </TouchableOpacity>
                    ))}
                  </View>

                  <TouchableOpacity
                    style={styles.editOutputShortcutBtn}
                    onPress={() => setActiveTab('customize')}
                    activeOpacity={0.8}
                  >
                    <Ionicons name="create-outline" size={14} color={colors.primary} />
                    <Text style={styles.editOutputShortcutText}>Edit Output</Text>
                  </TouchableOpacity>
                </View>

                {/* Quick Social Actions Bar */}
                <View style={styles.quickShareStrip}>
                  <Text style={styles.quickShareLabel}>QUICK EXPORT:</Text>
                  <TouchableOpacity style={styles.quickActionPill} onPress={handleCopyAscii}>
                    <Ionicons name="copy-outline" size={13} color={colors.textPrimary} />
                    <Text style={styles.quickActionPillText}>Copy ASCII Box</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.quickActionPill} onPress={handleCopyMarkdown}>
                    <Ionicons name="logo-markdown" size={13} color={colors.textPrimary} />
                    <Text style={styles.quickActionPillText}>Markdown</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.quickActionPill} onPress={handleShareTwitter}>
                    <Ionicons name="logo-twitter" size={13} color="#1da1f2" />
                    <Text style={styles.quickActionPillText}>Post to X</Text>
                  </TouchableOpacity>
                  {Platform.OS === 'web' && (
                    <TouchableOpacity style={styles.quickActionPill} onPress={handleDownloadSvg}>
                      <Ionicons name="download-outline" size={13} color={colors.accentPurple} />
                      <Text style={styles.quickActionPillText}>SVG Image</Text>
                    </TouchableOpacity>
                  )}
                </View>
              </View>
            )}

            {/* 2. CUSTOMIZE TAB */}
            {activeTab === 'customize' && (
              <View style={styles.tabContent}>
                <View style={styles.settingsGrid}>
                  {/* Machine Presets Header */}
                  <View style={styles.formGroup}>
                    <View style={styles.labelWithActions}>
                      <Text style={styles.inputLabel}>SIMULATED ENVIRONMENT & HOST</Text>
                      <View style={styles.presetButtons}>
                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() => applyMachinePreset('ethan', 'macbook-pro', '~', '$')}
                        >
                          <Text style={styles.presetBtnText}>MacBook</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() => applyMachinePreset('root', 'prod-api-01', '/etc', '#')}
                        >
                          <Text style={styles.presetBtnText}>Prod Root</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() => applyMachinePreset('ubuntu', 'aws-ec2', '~/app', '$')}
                        >
                          <Text style={styles.presetBtnText}>AWS EC2</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() => applyMachinePreset('dev', 'archlinux', '~', '❯')}
                        >
                          <Text style={styles.presetBtnText}>Starship ❯</Text>
                        </TouchableOpacity>
                      </View>
                    </View>
                  </View>

                  {/* Username & Hostname Row */}
                  <View style={styles.rowTwoCols}>
                    <View style={styles.formGroup}>
                      <Text style={styles.inputLabel}>USERNAME</Text>
                      <TextInput
                        style={styles.textInput}
                        value={username}
                        onChangeText={handleUsernameChange}
                        placeholder="e.g. ethan, root, dev"
                        placeholderTextColor={colors.textMuted}
                        autoCapitalize="none"
                        autoCorrect={false}
                      />
                    </View>

                    <View style={styles.formGroup}>
                      <Text style={styles.inputLabel}>HOSTNAME</Text>
                      <TextInput
                        style={styles.textInput}
                        value={hostname}
                        onChangeText={handleHostnameChange}
                        placeholder="e.g. devvault, macbook, k8s-node"
                        placeholderTextColor={colors.textMuted}
                        autoCapitalize="none"
                        autoCorrect={false}
                      />
                    </View>
                  </View>

                  {/* CWD and Prompt Symbol Row */}
                  <View style={styles.rowTwoCols}>
                    <View style={styles.formGroup}>
                      <Text style={styles.inputLabel}>WORKING DIR (CWD)</Text>
                      <TextInput
                        style={styles.textInput}
                        value={cwd}
                        onChangeText={handleCwdChange}
                        placeholder="e.g. ~, ~/projects, /etc"
                        placeholderTextColor={colors.textMuted}
                        autoCapitalize="none"
                        autoCorrect={false}
                      />
                    </View>

                    <View style={styles.formGroup}>
                      <Text style={styles.inputLabel}>PROMPT SYMBOL</Text>
                      <View style={styles.symbolSelectorRow}>
                        {['$', '#', '❯', '>'].map((sym) => (
                          <TouchableOpacity
                            key={sym}
                            style={[
                              styles.symbolChip,
                              promptSymbol === sym && styles.symbolChipActive,
                            ]}
                            onPress={() => handleSymbolChange(sym)}
                          >
                            <Text
                              style={[
                                styles.symbolChipText,
                                promptSymbol === sym && styles.symbolChipTextActive,
                              ]}
                            >
                              {sym}
                            </Text>
                          </TouchableOpacity>
                        ))}
                      </View>
                    </View>
                  </View>

                  {/* Prompt & Duration Row */}
                  <View style={styles.rowTwoCols}>
                    <View style={styles.formGroup}>
                      <Text style={styles.inputLabel}>FULL SHELL PROMPT</Text>
                      <TextInput
                        style={styles.textInput}
                        value={prompt}
                        onChangeText={setPrompt}
                        placeholder="e.g. dev@vault:~$ or ❯"
                        placeholderTextColor={colors.textMuted}
                        autoCapitalize="none"
                        autoCorrect={false}
                      />
                    </View>

                    <View style={styles.formGroup}>
                      <Text style={styles.inputLabel}>SIMULATED DURATION</Text>
                      <TextInput
                        style={styles.textInput}
                        value={duration}
                        onChangeText={setDuration}
                        placeholder="e.g. 120ms or 1.4s"
                        placeholderTextColor={colors.textMuted}
                        autoCapitalize="none"
                      />
                    </View>
                  </View>

                  {/* Theme Selector */}
                  <View style={styles.formGroup}>
                    <Text style={styles.inputLabel}>CARD GLOW THEME (SOCIAL SHARING)</Text>
                    <View style={styles.themeSelectorRow}>
                      {[
                        { key: 'cyberpunk', label: 'Cyberpunk', dot: '#58a6ff' },
                        { key: 'tokyo', label: 'Tokyo Night', dot: '#7aa2f7' },
                        { key: 'dracula', label: 'Dracula', dot: '#bd93f9' },
                        { key: 'matrix', label: 'Matrix', dot: '#3fb950' },
                        { key: 'minimal', label: 'Obsidian', dot: '#6e7681' },
                      ].map((t) => (
                        <TouchableOpacity
                          key={t.key}
                          style={[styles.themeChip, theme === t.key && styles.themeChipActive]}
                          onPress={() => setTheme(t.key as ThemeMode)}
                        >
                          <View style={[styles.themeDot, { backgroundColor: t.dot }]} />
                          <Text style={[styles.themeChipText, theme === t.key && styles.themeChipTextActive]}>
                            {t.label}
                          </Text>
                        </TouchableOpacity>
                      ))}
                    </View>
                  </View>

                  {/* Terminal Comment / Annotation Field */}
                  <View style={styles.formGroup}>
                    <View style={styles.labelWithActions}>
                      <Text style={styles.inputLabel}>TERMINAL COMMENT / ANNOTATION</Text>
                      <View style={styles.presetButtons}>
                        {snippet.description ? (
                          <TouchableOpacity
                            style={styles.presetBtn}
                            onPress={() => setComment(snippet.description)}
                          >
                            <Text style={styles.presetBtnText}>Use Description</Text>
                          </TouchableOpacity>
                        ) : null}
                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() => setComment('Verify environment before running')}
                        >
                          <Text style={styles.presetBtnText}>Note</Text>
                        </TouchableOpacity>
                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() => setComment('Requires root / sudo privileges')}
                        >
                          <Text style={styles.presetBtnText}>Root Warning</Text>
                        </TouchableOpacity>
                        {comment ? (
                          <TouchableOpacity
                            style={styles.presetBtn}
                            onPress={() => setComment('')}
                          >
                            <Text style={styles.presetBtnText}>Clear</Text>
                          </TouchableOpacity>
                        ) : null}
                      </View>
                    </View>

                    <TextInput
                      style={styles.textInput}
                      value={comment}
                      onChangeText={setComment}
                      placeholder="e.g. Clean up dangling docker images to reclaim disk space"
                      placeholderTextColor={colors.textMuted}
                      autoCapitalize="none"
                      autoCorrect={false}
                    />
                    <Text style={styles.fieldHelpText}>
                      Renders as a shell comment (# note) in the terminal emulation preview, ASCII card, markdown, and SVG exports.
                    </Text>
                  </View>

                  {/* Expected Output Editor */}
                  <View style={styles.formGroup}>
                    <View style={styles.labelWithActions}>
                      <Text style={styles.inputLabel}>EXPECTED CLI OUTPUT (STDOUT / STDERR)</Text>
                      {/* Presets */}
                      <View style={styles.presetButtons}>
                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() =>
                            setExpectedOutput(
                              `✔ Operation completed successfully.\n  Processed 14 items with exit code 0.`
                            )
                          }
                        >
                          <Text style={styles.presetBtnText}>Success</Text>
                        </TouchableOpacity>

                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() =>
                            setExpectedOutput(
                              `{\n  "status": 200,\n  "data": "healthy",\n  "timestamp": ${Date.now()}\n}`
                            )
                          }
                        >
                          <Text style={styles.presetBtnText}>JSON</Text>
                        </TouchableOpacity>

                        <TouchableOpacity
                          style={styles.presetBtn}
                          onPress={() =>
                            setExpectedOutput(
                              `ID          NAME              STATUS     AGE\n10492       api-prod-worker   RUNNING    14m\n10493       redis-primary     HEALTHY    2h`
                            )
                          }
                        >
                          <Text style={styles.presetBtnText}>Table</Text>
                        </TouchableOpacity>
                      </View>
                    </View>

                    <TextInput
                      style={[styles.textInput, styles.outputTextArea]}
                      value={expectedOutput}
                      onChangeText={setExpectedOutput}
                      multiline
                      numberOfLines={6}
                      placeholder="Type the simulated command line output here..."
                      placeholderTextColor={colors.textMuted}
                      autoCapitalize="none"
                      autoCorrect={false}
                    />
                  </View>

                  {/* Save to Snippet Button */}
                  <TouchableOpacity
                    style={[styles.saveBtn, saveSuccess && styles.saveBtnSuccess]}
                    onPress={handleSaveOutput}
                    activeOpacity={0.8}
                  >
                    <Ionicons
                      name={saveSuccess ? 'checkmark-circle' : 'save-outline'}
                      size={16}
                      color={colors.textInverse}
                    />
                    <Text style={styles.saveBtnText}>
                      {saveSuccess ? 'Saved to Recipe!' : 'Save Expected Output to Recipe'}
                    </Text>
                  </TouchableOpacity>
                </View>
              </View>
            )}

            {/* 3. SHARE TAB */}
            {activeTab === 'share' && (
              <View style={styles.tabContent}>
                <Text style={styles.shareHeading}>Social-Friendly Sharing Formats</Text>
                <Text style={styles.shareSubtitle}>
                  Instantly format your command emulation to share on social feeds, docs, or developer chats.
                </Text>

                <View style={styles.shareCardsGrid}>
                  {/* Option 1: Unicode ASCII Box */}
                  <View style={styles.shareOptionCard}>
                    <View style={styles.shareOptionHeader}>
                      <View style={styles.shareOptionIconBox}>
                        <Ionicons name="code-slash" size={18} color={colors.primary} />
                      </View>
                      <View style={{ flex: 1 }}>
                        <Text style={styles.shareOptionTitle}>ASCII Terminal Box</Text>
                        <Text style={styles.shareOptionDesc}>
                          High-fidelity Unicode frame. Renders natively on GitHub, Discord, Reddit, & Slack.
                        </Text>
                      </View>
                    </View>
                    <TouchableOpacity style={styles.shareActionBtn} onPress={handleCopyAscii}>
                      <Ionicons name="copy-outline" size={15} color={colors.primary} />
                      <Text style={styles.shareActionBtnText}>Copy ASCII Card</Text>
                    </TouchableOpacity>
                  </View>

                  {/* Option 2: Markdown Code Block */}
                  <View style={styles.shareOptionCard}>
                    <View style={styles.shareOptionHeader}>
                      <View style={styles.shareOptionIconBox}>
                        <Ionicons name="logo-markdown" size={18} color={colors.secondary} />
                      </View>
                      <View style={{ flex: 1 }}>
                        <Text style={styles.shareOptionTitle}>Markdown Codeblock</Text>
                        <Text style={styles.shareOptionDesc}>
                          Formatted with ````bash ... ```` ready for documentation and blogs.
                        </Text>
                      </View>
                    </View>
                    <TouchableOpacity style={styles.shareActionBtn} onPress={handleCopyMarkdown}>
                      <Ionicons name="copy-outline" size={15} color={colors.secondary} />
                      <Text style={[styles.shareActionBtnText, { color: colors.secondary }]}>
                        Copy Markdown
                      </Text>
                    </TouchableOpacity>
                  </View>

                  {/* Option 3: Twitter / X Post */}
                  <View style={styles.shareOptionCard}>
                    <View style={styles.shareOptionHeader}>
                      <View style={[styles.shareOptionIconBox, { backgroundColor: 'rgba(29, 161, 242, 0.15)' }]}>
                        <Ionicons name="logo-twitter" size={18} color="#1da1f2" />
                      </View>
                      <View style={{ flex: 1 }}>
                        <Text style={styles.shareOptionTitle}>Share on X / Twitter</Text>
                        <Text style={styles.shareOptionDesc}>
                          Pre-populates a tweet with the command, simulated output, and dev tags.
                        </Text>
                      </View>
                    </View>
                    <TouchableOpacity
                      style={[styles.shareActionBtn, { borderColor: '#1da1f2' }]}
                      onPress={handleShareTwitter}
                    >
                      <Ionicons name="open-outline" size={15} color="#1da1f2" />
                      <Text style={[styles.shareActionBtnText, { color: '#1da1f2' }]}>
                        Post to Twitter / X
                      </Text>
                    </TouchableOpacity>
                  </View>

                  {/* Option 4: LinkedIn Share */}
                  <View style={styles.shareOptionCard}>
                    <View style={styles.shareOptionHeader}>
                      <View style={[styles.shareOptionIconBox, { backgroundColor: 'rgba(10, 102, 194, 0.15)' }]}>
                        <Ionicons name="logo-linkedin" size={18} color="#0a66c2" />
                      </View>
                      <View style={{ flex: 1 }}>
                        <Text style={styles.shareOptionTitle}>Share on LinkedIn</Text>
                        <Text style={styles.shareOptionDesc}>
                          Share your workflow tip with professional developer networks.
                        </Text>
                      </View>
                    </View>
                    <TouchableOpacity
                      style={[styles.shareActionBtn, { borderColor: '#0a66c2' }]}
                      onPress={handleShareLinkedIn}
                    >
                      <Ionicons name="open-outline" size={15} color="#0a66c2" />
                      <Text style={[styles.shareActionBtnText, { color: '#0a66c2' }]}>
                        Share to LinkedIn
                      </Text>
                    </TouchableOpacity>
                  </View>

                  {/* Option 5: SVG Card Download (Web) */}
                  {Platform.OS === 'web' && (
                    <View style={styles.shareOptionCard}>
                      <View style={styles.shareOptionHeader}>
                        <View style={[styles.shareOptionIconBox, { backgroundColor: 'rgba(210, 168, 255, 0.15)' }]}>
                          <Ionicons name="image-outline" size={18} color={colors.accentPurple} />
                        </View>
                        <View style={{ flex: 1 }}>
                          <Text style={styles.shareOptionTitle}>Vector SVG Image</Text>
                          <Text style={styles.shareOptionDesc}>
                            Download high-res vector graphics card with window controls and glow.
                          </Text>
                        </View>
                      </View>
                      <TouchableOpacity
                        style={[styles.shareActionBtn, { borderColor: colors.accentPurple }]}
                        onPress={handleDownloadSvg}
                      >
                        <Ionicons name="download-outline" size={15} color={colors.accentPurple} />
                        <Text style={[styles.shareActionBtnText, { color: colors.accentPurple }]}>
                          Download SVG Image
                        </Text>
                      </TouchableOpacity>
                    </View>
                  )}
                </View>
              </View>
            )}
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 820,
    maxHeight: '92%',
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? ({
          boxShadow: '0 20px 48px rgba(0, 0, 0, 0.6)',
        } as any)
      : {}),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  terminalIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(63, 185, 80, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    fontFamily: 'monospace',
  },
  headerSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
    fontFamily: 'monospace',
    marginTop: 2,
    maxWidth: 500,
  },
  closeBtn: {
    padding: 6,
    borderRadius: 6,
  },
  toastBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(63, 185, 80, 0.18)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(63, 185, 80, 0.3)',
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  toastText: {
    fontSize: 12,
    color: colors.accentGreen,
    fontFamily: 'monospace',
    fontWeight: '600',
  },
  tabBar: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  tabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabBtnActive: {
    borderBottomColor: colors.primary,
    backgroundColor: 'rgba(88, 166, 255, 0.05)',
  },
  tabText: {
    fontSize: 12,
    fontFamily: 'monospace',
    fontWeight: '600',
    color: colors.textMuted,
  },
  tabTextActive: {
    color: colors.primary,
  },
  body: {
    flex: 1,
  },
  scrollBody: {
    padding: 20,
  },
  tabContent: {
    gap: 16,
  },
  // Terminal Card Window
  terminalCard: {
    borderRadius: 10,
    borderWidth: 1.5,
    overflow: 'hidden',
  },
  terminalTitleBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  trafficLights: {
    flexDirection: 'row',
    gap: 7,
  },
  trafficDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
  },
  terminalTitleText: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: colors.textMuted,
    fontWeight: '600',
  },
  terminalStatusPills: {
    flexDirection: 'row',
    gap: 6,
  },
  exitStatusPill: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: 'rgba(63, 185, 80, 0.15)',
    borderWidth: 0.8,
    borderColor: colors.accentGreen,
  },
  exitStatusText: {
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: colors.accentGreen,
  },
  durationPill: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: 'rgba(88, 166, 255, 0.15)',
    borderWidth: 0.8,
    borderColor: colors.primary,
  },
  durationText: {
    fontSize: 10,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: colors.primary,
  },
  terminalBody: {
    padding: 16,
    minHeight: 180,
  },
  commentBlock: {
    marginBottom: 8,
    gap: 3,
  },
  terminalCommentText: {
    fontSize: 13,
    fontFamily: 'monospace',
    color: '#8b949e',
    fontStyle: 'italic',
  },
  cliLine: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  promptText: {
    fontSize: 13,
    fontFamily: 'monospace',
    color: colors.accentCyan,
    fontWeight: '700',
  },
  commandText: {
    fontSize: 13,
    fontFamily: 'monospace',
    color: colors.textPrimary,
    fontWeight: '600',
    flex: 1,
  },
  cursorText: {
    color: colors.primary,
    fontWeight: '900',
  },
  executingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    paddingVertical: 4,
  },
  spinnerIcon: {
    marginRight: 4,
  },
  executingText: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  outputBox: {
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
  },
  outputText: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'monospace',
    color: colors.textSecondary,
  },
  // Playback Controls
  playbackControls: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
  },
  replayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 6,
  },
  replayBtnText: {
    fontSize: 12,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: colors.textInverse,
  },
  speedButtonGroup: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  speedBtn: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  speedBtnActive: {
    backgroundColor: 'rgba(88, 166, 255, 0.2)',
  },
  speedBtnText: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: colors.textMuted,
    fontWeight: '600',
  },
  speedBtnTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  editOutputShortcutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginLeft: 'auto',
    backgroundColor: 'rgba(88, 166, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(88, 166, 255, 0.3)',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  editOutputShortcutText: {
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: '600',
    color: colors.primary,
  },
  // Quick Share Strip
  quickShareStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  quickShareLabel: {
    fontSize: 10,
    fontFamily: 'monospace',
    color: colors.textMuted,
    fontWeight: '700',
    marginRight: 4,
  },
  quickActionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
  },
  quickActionPillText: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: colors.textPrimary,
  },
  // Customization Grid
  settingsGrid: {
    gap: 16,
  },
  rowTwoCols: {
    flexDirection: 'row',
    gap: 16,
  },
  formGroup: {
    flex: 1,
    gap: 6,
  },
  inputLabel: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: colors.textSecondary,
    fontWeight: '700',
  },
  labelWithActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  presetButtons: {
    flexDirection: 'row',
    gap: 6,
  },
  presetBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  presetBtnText: {
    fontSize: 10,
    fontFamily: 'monospace',
    color: colors.primary,
  },
  symbolSelectorRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    height: 40,
  },
  symbolChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: colors.border,
  },
  symbolChipActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(88, 166, 255, 0.15)',
  },
  symbolChipText: {
    fontSize: 13,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: colors.textSecondary,
  },
  symbolChipTextActive: {
    color: colors.primary,
  },
  textInput: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: colors.textPrimary,
    fontFamily: 'monospace',
    fontSize: 13,
  },
  fieldHelpText: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: colors.textMuted,
    marginTop: 2,
    lineHeight: 15,
  },
  outputTextArea: {
    minHeight: 120,
    lineHeight: 18,
    textAlignVertical: 'top',
  },
  themeSelectorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  themeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  themeChipActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(88, 166, 255, 0.12)',
  },
  themeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  themeChipText: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: colors.textSecondary,
  },
  themeChipTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.accentGreen,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  saveBtnSuccess: {
    backgroundColor: '#2ea043',
  },
  saveBtnText: {
    fontSize: 13,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: colors.textInverse,
  },
  // Social Share Tab
  shareHeading: {
    fontSize: 16,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: colors.textPrimary,
  },
  shareSubtitle: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: colors.textMuted,
    lineHeight: 17,
  },
  shareCardsGrid: {
    gap: 12,
    marginTop: 8,
  },
  shareOptionCard: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 14,
    gap: 12,
  },
  shareOptionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  shareOptionIconBox: {
    width: 34,
    height: 34,
    borderRadius: 6,
    backgroundColor: 'rgba(88, 166, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shareOptionTitle: {
    fontSize: 13,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: colors.textPrimary,
  },
  shareOptionDesc: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: colors.textSecondary,
    marginTop: 2,
    lineHeight: 16,
  },
  shareActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 8,
    borderRadius: 6,
  },
  shareActionBtnText: {
    fontSize: 12,
    fontFamily: 'monospace',
    fontWeight: '700',
    color: colors.primary,
  },
});
